name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build service
      run: |
        docker build -t $DOCKER_USERNAME/twilo-realtime:$IMAGE_TAG twilo-realtime
        docker push $DOCKER_USERNAME/twilo-realtime:$IMAGE_TAG
